services:
  uptime-kuma:
    image: docker.io/louislam/uptime-kuma:latest
    container_name: nasypeasy-uptime-kuma
    ports:
      - "3001:3001"
    volumes:
      - uptime-kuma-data:/app/data
    restart: unless-stopped

volumes:
  uptime-kuma-data:
