services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: nasypeasy-filebrowser
    ports:
      - "8080:8080"
    volumes:
      - /:/srv:ro
    environment:
      - FB_PORT=8080
