services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: nasypeasy-filebrowser
    ports:
      - "8080:80"
    volumes:
      - /:/srv:ro
    restart: unless-stopped
