services:
  filebrowser:
    image: docker.io/filebrowser/filebrowser:latest
    container_name: nasypeasy-filebrowser
    ports:
      - "8080:8080"
    volumes:
      - $FILES_DATA:/srv:Z
    environment:
      - FB_PORT=8080
      #- FB_USERNAME=admin
      #- FB_PASSWORD=admin
