services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: nasypeasy-vaultwarden
    ports:
      - "8081:80"
    volumes:
      - vaultwarden-data:/data
    environment:
      SIGNUPS_ALLOWED: "false"
      DOMAIN: $DOMAIN
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent http://localhost:80/alive || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - caddy

  caddy:
    image: caddy:latest
    container_name: nasypeasy-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:Z
      - caddy-data:/data
    environment:
      DOMAIN: $DOMAIN
    depends_on:
      - vaultwarden
    networks:
      - caddy

volumes:
  vaultwarden-data:
  caddy-data:

networks:
  caddy:
